#ifndef PREPROCESSING_CONDITIONAL_INCLUDES_SUPPORT_INCLUDE_NEXT_FIRST_NEXT_HEADER_H
#define PREPROCESSING_CONDITIONAL_INCLUDES_SUPPORT_INCLUDE_NEXT_FIRST_NEXT_HEADER_H

#define FIRST_HEADER_PROCESSED

// TODO DWYU cannot evaluate '__has_include_next'
// #if __has_include_next(<next_header.h>)
// #define FIRST_HEADER_SEES_NEXT
// #endif

#include_next <next_header.h>

#endif // PREPROCESSING_CONDITIONAL_INCLUDES_SUPPORT_INCLUDE_NEXT_FIRST_NEXT_HEADER_H
