load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "lib_a",
    hdrs = ["lib.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "lib_b",
    hdrs = ["lib.h"],
    visibility = ["//visibility:public"],
)
