#ifndef MISSING_DEPENDENCY_WORKSPACE_AMBIGUOUS_LIB_LIB_H
#define MISSING_DEPENDENCY_WORKSPACE_AMBIGUOUS_LIB_LIB_H

int doSomething() {
    return 42;
}

#endif // MISSING_DEPENDENCY_WORKSPACE_AMBIGUOUS_LIB_LIB_H
