[environment]
extra-paths = ["./test/aspect"]

[rules]
# Does not work with how the dynamically load modules for integration testing
unresolved-attribute = "ignore"
# ty cannot discover our bazelized third_party dependencies
unresolved-import = "ignore"
