#ifndef MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_SUB_SUB_1_H
#define MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_SUB_SUB_1_H

int doSub1() {
    return 1;
}

#endif // MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_SUB_SUB_1_H
