#ifndef MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_SUB_SUB_2_H
#define MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_SUB_SUB_2_H

int doSub2() {
    return 2;
}

#endif // MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_SUB_SUB_2_H
