#ifndef MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_SUB_SUB_3_H
#define MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_SUB_SUB_3_H

int doSub3() {
    return 3;
}

#endif // MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_SUB_SUB_3_H
