#ifndef MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_SUB_SUB_4_H
#define MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_SUB_SUB_4_H

int doSub4() {
    return 4;
}

#endif // MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_SUB_SUB_4_H
