#ifndef MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_SUB_SUB_5_H
#define MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_SUB_SUB_5_H

int doSub5() {
    return 5;
}

#endif // MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_SUB_SUB_5_H
