load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "buildozer_executor_test",
    srcs = ["buildozer_executor_test.py"],
    deps = ["//src/apply_fixes:lib"],
)

py_test(
    name = "summary_test",
    srcs = ["summary_test.py"],
    deps = ["//src/apply_fixes:lib"],
)
