#ifndef MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_INCLUDES_H
#define MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_INCLUDES_H

int doIncludes() {
    return 1;
}

#endif // MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_INCLUDES_H
