#ifndef MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_VIRTUAL_2_H
#define MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_VIRTUAL_2_H

int doVirtual2() {
    return 2;
}

#endif // MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_VIRTUAL_2_H
