#ifndef MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_VIRTUAL_1_H
#define MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_VIRTUAL_1_H

int doVirtual1() {
    return 1;
}

#endif // MISSING_DEPENDENCY_WORKSPACE_VIRTUAL_INCLUDES_VIRTUAL_1_H
