#ifndef MISSING_DEPENDENCY_WORKSPACE_PRIVATE_HEADER_PRIVATE_BAR_H
#define MISSING_DEPENDENCY_WORKSPACE_PRIVATE_HEADER_PRIVATE_BAR_H

int doPrivateStuff() {
    return 42;
}

#endif // MISSING_DEPENDENCY_WORKSPACE_PRIVATE_HEADER_PRIVATE_BAR_H
