load("//dwyu/cc_toolchain_headers:cc_toolchain_headers.bzl", "dwyu_gather_cc_toolchain_headers")
load(":cc_toolchain_headers_stub.bzl", "cc_toolchain_headers_stub")

dwyu_gather_cc_toolchain_headers(
    name = "cc_toolchain_headers",
    visibility = ["//visibility:public"],
)

cc_toolchain_headers_stub(
    name = "cc_toolchain_headers_stub",
    visibility = ["//visibility:public"],
)
