#ifndef MISSING_DEPENDENCY_WORKSPACE_EXTERNAL_DEP_FOO_H
#define MISSING_DEPENDENCY_WORKSPACE_EXTERNAL_DEP_FOO_H

int doFoo() {
    return 1337;
}

#endif // MISSING_DEPENDENCY_WORKSPACE_EXTERNAL_DEP_FOO_H
