name: 'Prepare Buildozer'
description: 'Download buildozer and make it available on PATH'
inputs:
  version:
    description: 'Buildozer version'
    required: true
runs:
  using: "composite"
  steps:
    - name: Construct buildozer URL
      shell: bash
      run: |
        BASE_URL="https://github.com/bazelbuild/buildtools/releases/download/v${{ inputs.version }}"
        if [[ "${RUNNER_OS}" == "Linux" ]]; then
          BUILDOZER_URL="${BASE_URL}/buildozer-linux-amd64"
        elif [ "${RUNNER_OS}" == "macOS" ]; then
          BUILDOZER_URL="${BASE_URL}/buildozer-darwin-amd64"
        elif [ "${RUNNER_OS}" == "Windows" ]; then
          BUILDOZER_URL="${BASE_URL}/buildozer-windows-amd64.exe"
        else
          echo "'${RUNNER_OS}' is not supported"
          exit 1
        fi
        echo "BUILDOZER_URL=${BUILDOZER_URL}" >> $GITHUB_ENV
    - name: Setup buildozer
      if: runner.os != 'Windows'
      shell: bash
      run: |
        wget --no-verbose "${BUILDOZER_URL}" -O "/usr/local/bin/buildozer"
        chmod +x "/usr/local/bin/buildozer"
    - name: Setup buildozer
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        New-Item -Path "D:\" -Name "bin" -ItemType Directory
        Invoke-WebRequest -Uri $Env:BUILDOZER_URL -OutFile "D:\bin\buildozer.exe"

        # Make buildozer available on PATH for subsequent actions
        echo "D:\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
