workspace(name = "dwyu_examples")

local_repository(
    name = "depend_on_what_you_use",
    path = "../../",
)

load("@depend_on_what_you_use//:setup_step_1.bzl", "setup_step_1")

setup_step_1()

load("@depend_on_what_you_use//:setup_step_2.bzl", "setup_step_2")

setup_step_2()
