load("@rules_python//python:py_library.bzl", "py_library")

py_library(
    name = "support",
    testonly = True,
    srcs = [
        "bazel.py",
        "platform.py",
        "result.py",
    ],
    visibility = ["//visibility:public"],
)
