load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "foo",
    srcs = [
        "foo.cpp",
        "impl/foo.cpp",
    ],
    hdrs = [
        "foo.h",
        "impl/foo.h",
    ],
)
