cc_library(
    name = "foo",
    hdrs = ["foo.h"],
    deps = [
        ":bar_a",
        ":bar_b",
    ],
)

cc_library(
    name = "bar_a",
    hdrs = ["bar.h"],
)

cc_library(
    name = "bar_b",
    hdrs = ["bar.h"],
)
