load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "extract_includes",
    srcs = ["extract_includes.cpp"],
    hdrs = ["extract_includes.h"],
    visibility = ["//dwyu/aspect/private/preprocessing:__subpackages__"],
)
