workspace(name = "dwyu_examples")

local_repository(
    name = "depend_on_what_you_use",
    path = "../",
)

load("@depend_on_what_you_use//:setup_step_1.bzl", "setup_step_1")

setup_step_1()

load("@depend_on_what_you_use//:setup_step_2.bzl", "setup_step_2")

setup_step_2()

#
# One can use DWYU without the content below. The hermetic Python toolchain merely increases the reproducibility when
# executing the examples as integration test.
#

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

# Keep in sync with //examples/MODULE.bazel
maybe(
    http_archive,
    name = "rules_python",
    sha256 = "d70cd72a7a4880f0000a6346253414825c19cdd40a28289bdf67b8e6480edff8",
    strip_prefix = "rules_python-0.28.0",
    urls = ["https://github.com/bazelbuild/rules_python/releases/download/0.28.0/rules_python-0.28.0.tar.gz"],
)

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python",
    python_version = "3.8",
)
