workspace(name = "dwyu_examples")

local_repository(
    name = "depend_on_what_you_use",
    path = "../",
)

load("@depend_on_what_you_use//:setup_step_1.bzl", "setup_step_1")

setup_step_1()

load("@depend_on_what_you_use//:setup_step_2.bzl", "setup_step_2")

setup_step_2()

##
## One can use DWYU without the content below. The hermetic Python toolchain increases the reproducibility when
## executing the examples as integration test.
##
## We rely on rules_python provided by DWYU as dependency as we don't want to duplicate and keep in sync which version
## DWYU requests.
##

load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python",
    python_version = "3.8",
)

#
# Support to make the examples work
#

load("//:support/external_targets.bzl", "load_external_targets")

load_external_targets()
