workspace(name = "dwyu_examples")

##
## Public part of the examples
##

local_repository(
    name = "depend_on_what_you_use",
    path = "../",
)

load("@depend_on_what_you_use//:setup_step_1.bzl", "setup_step_1")

setup_step_1()

load("@depend_on_what_you_use//:setup_step_2.bzl", "setup_step_2")

setup_step_2()

##
## The content below is required for using the examples as tests, but is not required for using DWYU
##

# We rely on rules_python provided by DWYU as dependency as we don't want to duplicate and keep in sync the version
load("@rules_python//python:repositories.bzl", "python_register_toolchains")

python_register_toolchains(
    name = "python",
    python_version = "3.8",
)

load("//:support/external_targets.bzl", "load_external_targets")

load_external_targets()
