cc_library(
    name = "a",
    hdrs = ["a.h"],
    visibility = ["//test/aspect/defines:__pkg__"],
)

cc_library(
    name = "b",
    hdrs = ["b.h"],
    visibility = ["//test/aspect/defines:__pkg__"],
)
