load("//src/toolchain_headers:toolchain_headers.bzl", "dwyu_gather_cc_toolchain_headers")

dwyu_gather_cc_toolchain_headers(
    name = "toolchain_headers",
    visibility = ["//visibility:public"],
)
