load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "bar",
    srcs = [
        "bar.cpp",
        "impl/bar.cpp",
    ],
    hdrs = [
        "bar.h",
        "impl/bar.h",
    ],
)
