#ifndef MISSING_DEPENDENCY_WORKSPACE_EXTERNAL_DEP_SUB_DIR_BAR_H
#define MISSING_DEPENDENCY_WORKSPACE_EXTERNAL_DEP_SUB_DIR_BAR_H

int doBar() {
    return 42;
}

#endif // MISSING_DEPENDENCY_WORKSPACE_EXTERNAL_DEP_SUB_DIR_BAR_H
