workspace(name = "dwyu_aspect_integration_tests")

local_repository(
    name = "depend_on_what_you_use",
    path = "../../",
)

load("@depend_on_what_you_use//:setup_step_1.bzl", "setup_step_1")

setup_step_1()

load("@depend_on_what_you_use//:setup_step_2.bzl", "setup_step_2")

setup_step_2()

##
## Python toolchains for testing compatibility to various Python versions
##
## We rely on rules_python provided by DWYU as dependency, since we we do not profit from using a custom version.
##

load("@rules_python//python:repositories.bzl", "python_register_multi_toolchains")

# Choose different version via: --@rules_python//python/config_settings:python_version=X
python_register_multi_toolchains(
    name = "python",
    default_version = "3.8",
    python_versions = [
        "3.9",
        "3.10",
        "3.11",
        "3.12",
    ],
)

##
## Workspaces for test purposes
##

load("//complex_includes:ext_repo.bzl", "load_complex_includes_repo")
load("//external_repo:repo.bzl", "load_external_repo")
load("//skip_external_targets:external_dep.bzl", "load_external_dep")

load_external_repo()

load_complex_includes_repo()

load_external_dep()
