#ifndef MISSING_DEPENDENCY_WORKSPACE_OTHER_LIB_FOO_H
#define MISSING_DEPENDENCY_WORKSPACE_OTHER_LIB_FOO_H

int doOtherFoo() {
    return 1234;
};

#endif // MISSING_DEPENDENCY_WORKSPACE_OTHER_LIB_FOO_H
