#ifndef NEEDLESSLY_PUBLIC_DEPENDENCY_WORKSPACE_USING_C_H
#define NEEDLESSLY_PUBLIC_DEPENDENCY_WORKSPACE_USING_C_H

#include "lib_c.h"

int doSomethingPublic() {
    return 13;
}

#endif // NEEDLESSLY_PUBLIC_DEPENDENCY_WORKSPACE_USING_C_H
