load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "ext_bar",
    hdrs = ["some/dir/bar.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "ext_foo",
    hdrs = ["foo.h"],
    visibility = ["//visibility:public"],
)
