load("//src/utils:create_doc.bzl", "create_doc")

create_doc(
    name = "cc_info_mapping",
    out = "//docs:cc_info_mapping.md",
    input = "cc_info_mapping.bzl",
    deps = [
        "//src/cc_info_mapping/private:bzl_srcs",
        "//src/utils",
        "//src/utils:rules_cc_bzl_srcs",
    ],
)
