load("@rules_python//python:py_test.bzl", "py_test")

py_test(
    name = "bazel_query_test",
    srcs = ["bazel_query_test.py"],
    deps = ["//dwyu/apply_fixes:lib"],
)

py_test(
    name = "buildozer_executor_test",
    srcs = ["buildozer_executor_test.py"],
    deps = ["//dwyu/apply_fixes:lib"],
)

py_test(
    name = "get_dwyu_reports_test",
    srcs = ["get_dwyu_reports_test.py"],
    deps = ["//dwyu/apply_fixes:lib"],
)

py_test(
    name = "search_missing_deps_test",
    srcs = ["search_missing_deps_test.py"],
    deps = ["//dwyu/apply_fixes:lib"],
)

py_test(
    name = "summary_test",
    srcs = ["summary_test.py"],
    deps = ["//dwyu/apply_fixes:lib"],
)

py_test(
    name = "utils_test",
    srcs = ["utils_test.py"],
    deps = ["//dwyu/apply_fixes:lib"],
)
