#ifndef MISSING_DEPENDENCY_WORKSPACE_LIBS_PRIVATE_H
#define MISSING_DEPENDENCY_WORKSPACE_LIBS_PRIVATE_H

int doSthPrivate() {
    return 4 + 2;
}

#endif // MISSING_DEPENDENCY_WORKSPACE_LIBS_PRIVATE_H
