cc_binary(
    name = "use_lib_b",
    srcs = ["use_lib_b.cpp"],
    deps = ["//test/aspect/target_mapping/libs:a"],
)

cc_binary(
    name = "use_lib_c",
    srcs = ["use_lib_c.cpp"],
    deps = ["//test/aspect/target_mapping/libs:a"],
)
