load("@rules_python//python:py_binary.bzl", "py_binary")

py_binary(
    name = "parse_preprocessed_file",
    main = "main.py",
    srcs = ["main.py"],
    imports = ["../.."],
    visibility = ["//visibility:public"],
)
