def print_cc_info(cc_info):
    print("compilation_context")
    print("  defines                : {}".format(cc_info.compilation_context.defines))
    print("  direct_headers         : {}".format(cc_info.compilation_context.direct_headers))
    print("  direct_private_headers : {}".format(cc_info.compilation_context.direct_private_headers))
    print("  direct_public_headers  : {}".format(cc_info.compilation_context.direct_public_headers))
    print("  direct_textual_headers : {}".format(cc_info.compilation_context.direct_textual_headers))
    print("  framework_includes     : {}".format(cc_info.compilation_context.framework_includes))
    print("  headers                : {}".format(cc_info.compilation_context.headers))
    print("  includes               : {}".format(cc_info.compilation_context.includes))
    print("  local_defines          : {}".format(cc_info.compilation_context.local_defines))
    print("  quote_includes         : {}".format(cc_info.compilation_context.quote_includes))
    print("  system_includes        : {}".format(cc_info.compilation_context.system_includes))
